# Generated by Django 4.2.28 on 2026-02-06 01:19

from django.db import migrations, models
import madar_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('madar_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', madar_app.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('EMPLOYEE', 'Employee'), ('CHEF', 'Chef'), ('RH_SIMPLE', 'RH'), ('RH_SENIOR', 'Senior RH'), ('GRH', 'GRH')], default='EMPLOYEE', max_length=20),
        ),
    ]
