# Generated by Django 4.2.28 on 2026-02-06 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('madar_app', '0005_leaverequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplineFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of month representing the month')),
                ('warning_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_flags', to='madar_app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='AbsenceWarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('comment', models.TextField(blank=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absence_warnings', to='madar_app.employee')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_warnings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='disciplineflag',
            constraint=models.UniqueConstraint(fields=('employee', 'month'), name='unique_discipline_flag_per_month'),
        ),
        migrations.AddConstraint(
            model_name='absencewarning',
            constraint=models.UniqueConstraint(fields=('employee', 'date'), name='unique_absence_warning_per_day'),
        ),
    ]
