# Generated by Django 4.2.28 on 2026-02-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madar_app', '0008_document_documenttype_documenthistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='attendance_pin_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
