# Generated by Django 4.2.28 on 2026-02-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madar_app', '0009_user_attendance_pin_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='attendance_pin',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
