# Generated by Django 4.2.28 on 2026-03-03 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madar_app', '0016_message_messagingsettings_messageattachment_draft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
