# Generated by Django 4.2.28 on 2026-03-04 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madar_app', '0017_employee_profile_picture_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('EMPLOYEE', 'Employee'), ('CHEF', 'Chef'), ('RH_SIMPLE', 'RH'), ('RH_AGENT', 'RH Agent'), ('RH_SENIOR', 'Senior RH'), ('GRH', 'GRH')], default='EMPLOYEE', max_length=20),
        ),
    ]
