# Generated by Django 4.2.28 on 2026-03-04 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('madar_app', '0020_formationcatalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='formationcatalog',
            name='people_required',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='formationrequest',
            name='approved_formation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to='madar_app.formationcatalog'),
        ),
        migrations.AlterField(
            model_name='formationrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En Attente'), ('WAITING_FOR_PEOPLE', 'Waiting for People List'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté')], default='PENDING', max_length=30),
        ),
        migrations.CreateModel(
            name='FormationParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formation_participations', to='madar_app.employee')),
                ('formation_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='madar_app.formationrequest')),
            ],
            options={
                'ordering': ['added_at'],
                'unique_together': {('formation_request', 'employee')},
            },
        ),
    ]
