# Generated by Django 4.2.28 on 2026-03-06 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madar_app', '0026_user_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='contract_type',
            field=models.CharField(choices=[('CDD', 'CDD'), ('CDI', 'CDI'), ('STAGE', 'Stage')], default='CDI', max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hired_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
