# Generated by Django 4.2.28 on 2026-03-08 23:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('madar_app', '0028_message_importance_flags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_important_by_recipient',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_important_by_sender',
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('code', models.CharField(help_text='Unique service code (e.g., RH, INFO)', max_length=20, primary_key=True, serialize=False)),
                ('nomService', models.CharField(max_length=200, verbose_name='Nom du service')),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif')], default='ACTIF', max_length=10, verbose_name='Statut')),
                ('budget', models.DecimalField(decimal_places=2, help_text='Budget alloué (doit être >= 0)', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('serviceParentId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sous_services', to='madar_app.service', verbose_name='Service parent')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['code'],
            },
        ),
    ]
