# Generated by Django 4.2.28 on 2026-03-09 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('madar_app', '0031_job_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='target_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='madar_app.service'),
        ),
        migrations.AlterField(
            model_name='document',
            name='source_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_created', to='madar_app.service'),
        ),
        migrations.AlterField(
            model_name='document',
            name='target_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_received', to='madar_app.service'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='madar_app.service'),
        ),
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateDebut', models.DateField(help_text='Start date of the assignment', verbose_name='Date de début')),
                ('dateFin', models.DateField(blank=True, help_text='End date of the assignment (null = ongoing)', null=True, verbose_name='Date de fin')),
                ('typeAffectation', models.CharField(choices=[('TITULAIRE', 'Titulaire'), ('INTERIM', 'Intérim'), ('DETACHEMENT', 'Détachement')], default='TITULAIRE', max_length=20, verbose_name="Type d'affectation")),
                ('motif', models.CharField(blank=True, help_text='Reason for the assignment (e.g., replacement, project, etc.)', max_length=255, verbose_name='Motif')),
                ('estPrimaire', models.BooleanField(default=False, help_text="Is this the employee's main official post?", verbose_name='Affectation primaire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='madar_app.employee', verbose_name='Employé')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affectations', to='madar_app.job', verbose_name='Poste')),
            ],
            options={
                'verbose_name': 'Affectation',
                'verbose_name_plural': 'Affectations',
                'ordering': ['employee', '-estPrimaire', '-dateDebut'],
            },
        ),
        migrations.AddConstraint(
            model_name='affectation',
            constraint=models.CheckConstraint(check=models.Q(('dateFin__isnull', True), ('dateDebut__lte', models.F('dateFin')), _connector='OR'), name='affectation_date_logic'),
        ),
    ]
