# Generated by Django 4.2.28 on 2026-03-09 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madar_app', '0032_alter_announcement_target_service_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='affectation',
            constraint=models.UniqueConstraint(condition=models.Q(('estPrimaire', True)), fields=('employee',), name='unique_primary_affectation_per_employee'),
        ),
    ]
