# Generated by Django 4.2.28 on 2026-03-09 00:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('madar_app', '0033_affectation_unique_primary_affectation_per_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('code', models.CharField(help_text='Short unique identifier (e.g., CA, CM, MAT)', max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='Code')),
                ('libelle', models.CharField(help_text='Displayed name (e.g., Congé Annuel, Congé Maladie)', max_length=100, verbose_name='Libellé')),
                ('nbrJoursDroit', models.IntegerField(help_text='Number of days allowed per year', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Nombre de jours de droit')),
                ('estPayant', models.BooleanField(default=True, help_text='Whether the leave is paid', verbose_name='Est payant')),
                ('reconductible', models.BooleanField(default=False, help_text='Can unused days carry to next year?', verbose_name='Reconductible')),
                ('delaiPreavis', models.IntegerField(default=0, help_text='Number of days notice required', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Délai de préavis')),
                ('justificatifRequis', models.BooleanField(default=False, help_text='Whether a supporting document is required', verbose_name='Justificatif requis')),
                ('sexeAutorise', models.CharField(choices=[('HOMME', 'Homme'), ('FEMME', 'Femme'), ('TOUS', 'Tous')], default='TOUS', help_text='Gender eligibility for this leave type', max_length=10, verbose_name='Sexe autorisé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Type de congé',
                'verbose_name_plural': 'Types de congé',
                'ordering': ['code'],
            },
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='type',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='type_old',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='leave_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leave_requests', to='madar_app.leavetype', verbose_name='Type de congé'),
        ),
    ]
