# Generated by Django 4.2.28 on 2026-03-09 00:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('madar_app', '0036_cleanup_leaverequest_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoldeConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField(help_text='Year for this leave balance (e.g., 2026)', validators=[django.core.validators.MinValueValidator(2000)], verbose_name='Année')),
                ('joursAcquis', models.DecimalField(decimal_places=1, default=0, help_text='Days acquired/earned for this year', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Jours acquis')),
                ('joursPris', models.DecimalField(decimal_places=1, default=0, help_text='Days taken/used', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Jours pris')),
                ('joursRestants', models.DecimalField(decimal_places=1, default=0, help_text='Remaining days (calculated)', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Jours restants')),
                ('joursReportes', models.DecimalField(decimal_places=1, default=0, help_text='Days carried over from previous year', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Jours reportés')),
                ('derniereMaj', models.DateTimeField(auto_now=True, help_text='Last time this balance was updated', verbose_name='Dernière mise à jour')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soldes_conge', to='madar_app.employee', verbose_name='Employé')),
                ('leaveType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soldes', to='madar_app.leavetype', verbose_name='Type de congé')),
            ],
            options={
                'verbose_name': 'Solde de congé',
                'verbose_name_plural': 'Soldes de congé',
                'ordering': ['employee', 'leaveType', '-annee'],
            },
        ),
        migrations.AddConstraint(
            model_name='soldeconge',
            constraint=models.UniqueConstraint(fields=('employee', 'leaveType', 'annee'), name='unique_solde_per_employee_leavetype_year'),
        ),
    ]
