# Generated by Django 4.2.28 on 2026-03-09 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('madar_app', '0037_soldeconge_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validator_role', models.CharField(choices=[('EMPLOYEE', 'Employee'), ('CHEF', 'Chef'), ('RH_SIMPLE', 'RH'), ('RH_AGENT', 'RH Agent'), ('RH_SENIOR', 'Senior RH'), ('GRH', 'GRH')], help_text='Role expected to validate this workflow step', max_length=20)),
                ('validation_order', models.PositiveIntegerField()),
                ('decision', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leave_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_workflow', to='madar_app.leaverequest')),
                ('validator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_validations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['leave_request', 'validation_order'],
            },
        ),
        migrations.AddConstraint(
            model_name='validationworkflow',
            constraint=models.UniqueConstraint(fields=('leave_request', 'validation_order'), name='unique_workflow_order_per_leave_request'),
        ),
    ]
