# Generated by Django 4.2.28 on 2026-03-09 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('madar_app', '0038_validationworkflow_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numVersion', models.PositiveIntegerField(verbose_name='Version Number')),
                ('comment', models.TextField(blank=True, help_text="Description of the change (e.g., 'Correction clause 3')")),
                ('file_path', models.FileField(upload_to='document_versions/')),
                ('size', models.BigIntegerField(help_text='File size in bytes')),
                ('is_current', models.BooleanField(default=False, help_text='Only one version can be current per document')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_versions', to='madar_app.employee')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='madar_app.document')),
            ],
            options={
                'ordering': ['-numVersion'],
            },
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('document',), name='unique_current_version_per_document', violation_error_message='A document can only have one current version.'),
        ),
    ]
