# Generated by Django 4.2.28 on 2026-03-09 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('madar_app', '0039_add_document_versioning'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='IN_PROGRESS', max_length=20)),
                ('validation_date', models.DateTimeField(blank=True, help_text='When the decision was made', null=True)),
                ('comment', models.TextField(blank=True, help_text='Explanation of the decision')),
                ('signature', models.CharField(blank=True, help_text='Electronic/digital signature of the validator', max_length=500)),
                ('step_order', models.PositiveIntegerField(help_text='Step number in the workflow (1, 2, 3...)')),
                ('is_active', models.BooleanField(default=False, help_text='Indicates the current validation step')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='madar_app.document')),
                ('validator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validations', to='madar_app.employee')),
            ],
            options={
                'ordering': ['step_order'],
            },
        ),
        migrations.AddConstraint(
            model_name='documentvalidation',
            constraint=models.UniqueConstraint(fields=('document', 'step_order'), name='unique_step_per_document', violation_error_message='Each step order must be unique per document.'),
        ),
        migrations.AddConstraint(
            model_name='documentvalidation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('document',), name='unique_active_step_per_document', violation_error_message='Only one validation step can be active per document.'),
        ),
    ]
