# Generated by Django 4.2.28 on 2026-03-09 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('madar_app', '0040_add_document_validation_workflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_datetime', models.DateTimeField(auto_now_add=True, help_text='Exact timestamp of the access')),
                ('action', models.CharField(choices=[('READ', 'Read'), ('DOWNLOAD', 'Download'), ('MODIFY', 'Modify'), ('DELETE', 'Delete'), ('SHARE', 'Share')], help_text='Action performed on the document', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address from which access was made', null=True)),
                ('result', models.BooleanField(default=True, help_text='True = access allowed, False = access denied')),
                ('details', models.TextField(blank=True, help_text='Additional details about the access attempt')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='madar_app.document')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Access Log',
                'verbose_name_plural': 'Document Access Logs',
                'ordering': ['-access_datetime'],
                'indexes': [models.Index(fields=['document', '-access_datetime'], name='madar_app_d_documen_b45082_idx'), models.Index(fields=['user', '-access_datetime'], name='madar_app_d_user_id_b40bb9_idx'), models.Index(fields=['action', '-access_datetime'], name='madar_app_d_action_2701ca_idx')],
            },
        ),
    ]
