# Generated by Django 4.2.28 on 2026-03-09 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madar_app', '0041_add_document_access_traceability'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentversion',
            name='checksum',
            field=models.CharField(blank=True, help_text='SHA256 checksum of this file version', max_length=64),
        ),
    ]
