# Generated by Django 4.2.28 on 2026-03-09 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madar_app', '0042_add_documentversion_checksum'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='confidentiality_level',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('INTERNAL', 'Internal'), ('CONFIDENTIAL', 'Confidential')], default='INTERNAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('VALIDATED', 'Validated'), ('REJECTED', 'Rejected'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20),
        ),
    ]
