# Generated by Django 4.2.28 on 2026-05-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madar_app', '0046_evaluations_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('EMPLOYEE', 'Employee'), ('CHEF', 'Chef'), ('RH_SIMPLE', 'RH'), ('RH_AGENT', 'RH Agent'), ('GRH', 'GRH')], default='EMPLOYEE', max_length=20),
        ),
        migrations.AlterField(
            model_name='validationworkflow',
            name='validator_role',
            field=models.CharField(choices=[('EMPLOYEE', 'Employee'), ('CHEF', 'Chef'), ('RH_SIMPLE', 'RH'), ('RH_AGENT', 'RH Agent'), ('GRH', 'GRH')], help_text='Role expected to validate this workflow step', max_length=20),
        ),
    ]
