# Generated by Django 4.2.28 on 2026-05-04 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madar_app', '0047_alter_user_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(blank=True, choices=[('RH', 'RH'), ('RH_FORMATION', 'RH Formation'), ('RH_CONGE', 'RH Congé'), ('DRH', 'DRH (Director RH)'), ('EMPLOYEE', 'Employee'), ('CHEF', 'Chef')], max_length=20, null=True, verbose_name='Role'),
        ),
        migrations.AddField(
            model_name='user',
            name='service',
            field=models.CharField(blank=True, choices=[('RH', 'RH'), ('INFORMATIQUE', 'Informatique'), ('FINANCE', 'Finance'), ('SALES', 'Sales'), ('OTHER', 'Other')], max_length=20, null=True, verbose_name='Service/Department'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('EMPLOYEE', 'Employee'), ('CHEF', 'Chef'), ('RH_SIMPLE', 'RH'), ('RH_AGENT', 'RH Agent'), ('GRH', 'GRH')], default='EMPLOYEE', max_length=20, null=True),
        ),
    ]
