# Generated by Django 4.2.28 on 2026-05-05 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madar_app', '0049_migrate_role_to_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(blank=True, choices=[('RH', 'RH'), ('RH_FORMATION', 'RH Formation'), ('RH_CONGE', 'RH Congé'), ('DRH', 'DRH (Directeur RH)'), ('EMPLOYEE', 'Employee'), ('CHEF', 'Chef')], max_length=20, null=True, verbose_name='Role'),
        ),
    ]
