# Generated by Django 4.2.28 on 2026-05-05 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madar_app', '0050_alter_employee_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='service',
            field=models.CharField(blank=True, choices=[('HR', 'HR'), ('FIN', 'Finance'), ('IT', 'IT'), ('OPS', 'Operations'), ('SALES', 'Sales')], max_length=20, null=True, verbose_name='Service/Department'),
        ),
    ]
