# Generated by Django 4.2.28 on 2026-05-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madar_app', '0051_update_servicechoices_to_match_service_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='confidentiality_level',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('CONFIDENTIAL', 'Confidential')], default='PUBLIC', max_length=20),
        ),
    ]
