# Generated by Django 4.2.28 on 2026-05-05 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madar_app', '0052_remove_internal_confidentiality'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='sexe',
            field=models.CharField(choices=[('HOMME', 'Homme'), ('FEMME', 'Femme')], default='HOMME', max_length=10, verbose_name='Sexe'),
        ),
    ]
