# Generated by Django 4.2.28 on 2026-05-08 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('madar_app', '0054_seed_hr_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceJustification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('NON_JUSTIFIE', 'Non justifié'), ('EN_COURS', 'En cours'), ('JUSTIFIE', 'Justifié'), ('NON_ACCEPTE', 'Justification non acceptée')], default='NON_JUSTIFIE', max_length=20)),
                ('document', models.FileField(blank=True, null=True, upload_to='absence_justifications/')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absence_justifications', to='madar_app.employee')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_justifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='absencejustification',
            constraint=models.UniqueConstraint(fields=('employee', 'date'), name='unique_absence_justification_per_day'),
        ),
    ]
