# Generated by Django 4.2.28 on 2026-05-14 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('madar_app', '0056_add_birth_date_to_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='madar_app.service'),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='position',
            unique_together={('name', 'service')},
        ),
    ]
