# Generated by Django 4.2.28 on 2026-05-14 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madar_app', '0057_add_service_to_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='contract_file',
            field=models.FileField(blank=True, null=True, upload_to='contracts/'),
        ),
    ]
