# Generated by Django 4.2.28 on 2026-05-16 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madar_app', '0058_add_contract_file_to_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AddField(
            model_name='employee',
            name='terminated_at',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin de contrat'),
        ),
    ]
