# Generated by Django 4.2.28 on 2026-05-16 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madar_app', '0059_add_employee_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='formationrequest',
            name='people_count',
            field=models.PositiveIntegerField(default=1, help_text='Number of employees needed'),
        ),
    ]
